Add bookings
DanSBol/java-shareit pull request #10
Opened 2024-05-12 13:45 UTC by DanSBol

2024-05-14 13:30 UTC, ErkinKasymaliev requested changes
привет, оставил комменты в основном в booking. Они аналогичны и для других доменов

2024-05-14 13:30 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                     @PathVariable(value = "bookingId") Long bookingId,
value = "bookingId" -- это необязательно если название перенной совпадает

2024-05-14 13:30 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                 @RequestBody BookingDto bookingDto) {
@Valid?

2024-05-14 13:30 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
а где то вы private прописываете... выберите одно

2024-05-14 13:30 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +            .start(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss").format(booking.getStartDate()))
DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss") в константу

2024-05-14 13:30 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        for (Booking booking : bookings) {
через stream().map()

2024-05-14 13:30 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            .filter(x -> x.getItem().getOwner().getId() == userId)
book -> book...

2024-05-14 13:30 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingStates.java
> +    PAST("**PAST**"),
зачем *?

2024-05-14 13:30 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/config/PersistenceConfig.java
> +        properties.put("hibernate.dialect", environment.getRequiredProperty("spring.jpa.properties.hibernate.dialect"));
почему бы не в application.properties

2024-05-14 13:30 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/config/WebConfig.java
> +public class WebConfig {
зачем?

2024-05-14 13:30 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +@Transactional(readOnly = true)
отсюда убрать

2024-05-14 13:30 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/config/PersistenceConfig.java
> +public class PersistenceConfig {
это зачем?

2024-05-14 19:14 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                     @PathVariable(value = "bookingId") Long bookingId,
Поправил

2024-05-14 19:15 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                 @RequestBody BookingDto bookingDto) {
Поправил

2024-05-14 19:20 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
Вообще убрал. Без этого контруктора все работает

2024-05-14 19:24 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +            .start(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss").format(booking.getStartDate()))
Добавил константу

2024-05-14 19:37 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        for (Booking booking : bookings) {
Поправил

2024-05-14 19:46 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/booking/BookingStates.java
> +    PAST("**PAST**"),
Не пригодилось. Незачем. Удалил

2024-05-14 19:51 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +@Transactional(readOnly = true)
Убрал

2024-05-14 19:53 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/config/PersistenceConfig.java
> +public class PersistenceConfig {
Скопипастил не подумав. Много где так (( Удалил

2024-05-14 19:55 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/config/PersistenceConfig.java
> +        properties.put("hibernate.dialect", environment.getRequiredProperty("spring.jpa.properties.hibernate.dialect"));
Не понял. Прошу пояснить

2024-05-14 19:59 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            .filter(x -> x.getItem().getOwner().getId() == userId)
Торможу. Не понял. Прошу пояснить.

2024-05-14 20:04 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/config/WebConfig.java
> +public class WebConfig {
Удалил

2024-05-14 20:06 UTC, DanSBol commented
Два замечания не понял. Прошу пояснить

2024-05-15 12:28 UTC, ErkinKasymaliev approved these changes
работа принята, только поправьте коммент перед мержем

2024-05-15 12:28 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/config/PersistenceConfig.java
> +public class PersistenceConfig {
вообще удалите класс, он не нужен, у вас есть application.properties -- его вполне достаточно

2024-05-15 12:29 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/config/PersistenceConfig.java
> +        properties.put("hibernate.dialect", environment.getRequiredProperty("spring.jpa.properties.hibernate.dialect"));
просто удалите класс, у вас есть application.properties - в нем все описано

2024-05-15 12:29 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            .filter(x -> x.getItem().getOwner().getId() == userId)
`filter(book -> book.getItem...`

2024-06-05 08:29 UTC, merged