Add item requests
DanSBol/java-shareit pull request #21
Opened 2024-06-21 05:13 UTC by DanSBol

2024-06-22 06:11 UTC, ErkinKasymaliev requested changes
привет, оставил комменты!
также не увидел тесты для BookingRepository и RequestRepository, добавьте их

2024-06-22 06:11 UTC, ErkinKasymaliev commented on htmlReport/css/coverage.css
> +/*
добавьте папку htmlReport в .gitignore

2024-06-22 06:11 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @RequestParam(required = false, defaultValue = "1000") Integer size) {
1000 много) пусть будет 20

2024-06-22 06:11 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @RequestParam(required = false, defaultValue = "1000") Integer size) {
в остальных местах тоже поправьте

2024-06-22 06:11 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Page<Booking> bookings = null;
давайте проверку size и from вынесем в отдельный метод

2024-06-22 11:01 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Page<Booking> bookings = null;
Готово

2024-06-22 11:02 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @RequestParam(required = false, defaultValue = "1000") Integer size) {
Поправил

2024-06-22 11:02 UTC, DanSBol commented on htmlReport/css/coverage.css
> +/*
Добавил

2024-06-22 11:03 UTC, DanSBol commented
Добавил BookingRepositoryTest и RequestRepositoryTest

2024-06-23 07:17 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-07-01 10:55 UTC, merged