Cоздать каркас приложения, а также разработать часть его веб-слоя (спринт 13)
DanSBol/java-shareit pull request #6
Opened 2024-04-21 00:27 UTC by DanSBol

2024-04-21 07:09 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-04-21 07:09 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (userService.getUser(userId).isPresent()) {
давайте все проверки уберем в сервис, в контроллерах оставим только их вызовы,
```
public ItemDto addItem(@RequestHeader("X-Sharer-User-Id") Long userId,
                           @Valid @RequestBody Item item) {
    return itemService.addItem(userId, item)
}
```

2024-04-21 07:09 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (items.containsKey(itemId)) {
```
@Override
public Optional<ItemDto> updateItem(long userId, long itemId, Item item) {
    if (!items.containsKey(itemId)) {
       throw new NotFoundException();
    }
    Item itemFromItems = items.get(itemId);
    if (itemFromItems.getOwner() == userId)
....
...
}
```

2024-04-21 07:09 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : items.values()) {
```
@Override
public Collection<ItemDto> getItemsByOwner(long userId) {
        return items.values.stream()
            .filter(item -> userId == item.getOwner())
            .map(ItemMapper::toItemDto)
            .collect(Collectors.toList());
}
```

2024-04-21 07:09 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Collection<ItemDto> search(String text) {
смотрите коммент в методе `getItemsByOwner()`

2024-04-21 07:09 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    long id;
модификаторы доступа

2024-04-21 07:09 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    long id;
модификаторы доступа

2024-04-21 07:09 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    long id;
модификаторы доступа

2024-04-21 09:24 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (userService.getUser(userId).isPresent()) {
Поправил

2024-04-21 09:25 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (items.containsKey(itemId)) {
Поправил

2024-04-21 09:55 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : items.values()) {
Поправил

2024-04-21 09:55 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Collection<ItemDto> search(String text) {
Готово

2024-04-21 09:58 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    long id;
Поставил private

2024-04-21 09:58 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    String name;
Поставил private

2024-04-21 09:58 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +
Поставил private

2024-04-21 09:59 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    public UserDto addUser(UserDto userDto) {
Поправил

2024-04-21 10:00 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        Collection<UserDto> collectionUserDto = new ArrayList<>();
Поправил

2024-04-21 10:01 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        if (users.containsKey(userId)) {
Поправил по аналогии с updateItem() в ItemServiceImpl

2024-04-21 10:01 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    long id;
Поставил private

2024-04-21 10:01 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    long id;
Поставил private

2024-04-21 10:05 UTC, DanSBol commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userService.updateUser(userId, userDto).orElseThrow(() -> new NotFoundException("User not found."));
Поправил аналогично ItemController (убрал проверки из контроллера)

2024-04-21 10:48 UTC, DanSBol commented
Нажав, как это часто бывает не туда, перенес твои комменты к себе в локальный репозиторий. Увидел в Idea (впервые), на всякий случай все почистил (думал, вдруг код не запустится %-). Потом перенес закоммиттил и запушил. В пуш реквест появились подозрительные сообщения о том, что я удалил твои комменты. Скрестив пальцы наудачу я очень надеюсь, что это ни на что не повлияет.

2024-04-22 07:16 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-04-30 11:31 UTC, merged